version: "3.9"

services:
  drachtio:
    image: drachtio/drachtio-server:latest
    container_name: drachtio
    network_mode: "bridge"
    ports:
      - "9022:9022/tcp" # drachtio control port
      - "5060:5060/udp" # SIP port
    volumes:
      - ./drachtio.conf:/etc/drachtio.conf:ro
    command: drachtio --contact "sip:*;transport=udp,tcp" --external-ip 159.20.69.20 --loglevel info
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
